// <auto-generated />
namespace ToDoList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _20210211B : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210211B));
        
        string IMigrationMetadata.Id
        {
            get { return "202102120203199_20210211B"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
